theme: jekyll-theme-minimal
title: Russian Agression
description: My country did not want to fight, but because of Russian aggression, the entire population rose up to confront the enemy.  Now we need the support of the world community.  Now the enemy is waging a massive information war, spreading large-scale disinformation, saying that we ourselves are shelling our cities and dimensional inhabitants.  He talks about the fact that there are no Russian troops on our streets.  Now, when the enemy is already trying to break into our capital, we want to show where clashes with the enemy army have already taken place.  We need to be heard!  Ukraine needs support!
 Stop Putin!
logo: tanks.jpg
#You can also add a logo from an image URL, as below
#logo: https://www.lawschool.cornell.edu/_cs_apps/pt_photo_gallery/uploads/mainphotogallery/fullsizeimage/Photogallery_Ithacapage_8.png

