theme: jekyll-theme-minimal
title: WAR
description: ця мапа розповідає про бойові дії.
logo: Taughannock.jpg
#You can also add a logo from an image URL, as below
#logo: https://www.lawschool.cornell.edu/_cs_apps/pt_photo_gallery/uploads/mainphotogallery/fullsizeimage/Photogallery_Ithacapage_8.png

